In [2]:
from metric import ConfusionMatrix, Classification_report

In [3]:
import torch

In [17]:
outputs = torch.randn(1,64, device=torch.device('cuda:0'))
outputs

tensor([[ 0.0572, -0.2431, -0.8920, -0.8272,  0.8638,  1.1155,  0.0392, -0.4967,
          0.1284,  0.7785, -0.9476,  0.2371,  0.1943,  0.4320, -0.7590,  0.3054,
          0.5740,  0.9450,  0.7417,  1.3863, -1.0016, -1.1097,  1.8747,  0.8750,
         -0.0865,  1.1798,  0.8766,  0.7564, -2.7366,  0.4447,  0.6127, -1.3814,
          0.0868,  0.5311,  1.7756,  0.0548,  0.1406, -0.9151,  1.1931, -0.7823,
          0.5021, -0.4774, -0.6074, -1.5083,  1.1093, -0.8801,  0.2433,  0.0724,
          1.1175,  0.7249,  1.3848, -0.0630, -1.7341,  0.2833, -1.2288,  1.1466,
         -1.2542,  0.1496,  0.4836, -1.6430,  0.9462,  3.0024, -1.3106,  1.3999]],
       device='cuda:0')

In [18]:
outputs1 = torch.randn(1,64, device=torch.device('cuda:0'))
outputs2 = torch.cat([outputs, outputs1], dim=1)

In [19]:
outputs2

tensor([[ 5.7221e-02, -2.4306e-01, -8.9203e-01, -8.2719e-01,  8.6376e-01,
          1.1155e+00,  3.9215e-02, -4.9666e-01,  1.2844e-01,  7.7854e-01,
         -9.4759e-01,  2.3715e-01,  1.9429e-01,  4.3205e-01, -7.5901e-01,
          3.0543e-01,  5.7399e-01,  9.4501e-01,  7.4169e-01,  1.3863e+00,
         -1.0016e+00, -1.1097e+00,  1.8747e+00,  8.7505e-01, -8.6521e-02,
          1.1798e+00,  8.7663e-01,  7.5637e-01, -2.7366e+00,  4.4466e-01,
          6.1270e-01, -1.3814e+00,  8.6757e-02,  5.3115e-01,  1.7756e+00,
          5.4765e-02,  1.4058e-01, -9.1508e-01,  1.1931e+00, -7.8226e-01,
          5.0210e-01, -4.7745e-01, -6.0741e-01, -1.5083e+00,  1.1093e+00,
         -8.8009e-01,  2.4334e-01,  7.2373e-02,  1.1175e+00,  7.2491e-01,
          1.3848e+00, -6.2988e-02, -1.7341e+00,  2.8326e-01, -1.2288e+00,
          1.1466e+00, -1.2542e+00,  1.4961e-01,  4.8356e-01, -1.6430e+00,
          9.4617e-01,  3.0024e+00, -1.3106e+00,  1.3999e+00,  2.0522e-01,
          1.3063e+00, -8.3263e-01,  1.

In [20]:
outputs2.shape

torch.Size([1, 128])

In [21]:
outputs3 = torch.randn(1,0, device=torch.device('cuda:0'))
outputs3

tensor([], device='cuda:0', size=(1, 0))

In [22]:
outputs3 = torch.cat([outputs3, outputs2], dim=1)
outputs3

tensor([[ 5.7221e-02, -2.4306e-01, -8.9203e-01, -8.2719e-01,  8.6376e-01,
          1.1155e+00,  3.9215e-02, -4.9666e-01,  1.2844e-01,  7.7854e-01,
         -9.4759e-01,  2.3715e-01,  1.9429e-01,  4.3205e-01, -7.5901e-01,
          3.0543e-01,  5.7399e-01,  9.4501e-01,  7.4169e-01,  1.3863e+00,
         -1.0016e+00, -1.1097e+00,  1.8747e+00,  8.7505e-01, -8.6521e-02,
          1.1798e+00,  8.7663e-01,  7.5637e-01, -2.7366e+00,  4.4466e-01,
          6.1270e-01, -1.3814e+00,  8.6757e-02,  5.3115e-01,  1.7756e+00,
          5.4765e-02,  1.4058e-01, -9.1508e-01,  1.1931e+00, -7.8226e-01,
          5.0210e-01, -4.7745e-01, -6.0741e-01, -1.5083e+00,  1.1093e+00,
         -8.8009e-01,  2.4334e-01,  7.2373e-02,  1.1175e+00,  7.2491e-01,
          1.3848e+00, -6.2988e-02, -1.7341e+00,  2.8326e-01, -1.2288e+00,
          1.1466e+00, -1.2542e+00,  1.4961e-01,  4.8356e-01, -1.6430e+00,
          9.4617e-01,  3.0024e+00, -1.3106e+00,  1.3999e+00,  2.0522e-01,
          1.3063e+00, -8.3263e-01,  1.

In [23]:
outputs3.shape

torch.Size([1, 128])

In [24]:
outputs3 = torch.cat([outputs3, outputs2], dim=1)
outputs3.shape

torch.Size([1, 256])

In [41]:
outputs4 = outputs3.reshape(256,-1)
outputs4

tensor([[ 5.7221e-02],
        [-2.4306e-01],
        [-8.9203e-01],
        [-8.2719e-01],
        [ 8.6376e-01],
        [ 1.1155e+00],
        [ 3.9215e-02],
        [-4.9666e-01],
        [ 1.2844e-01],
        [ 7.7854e-01],
        [-9.4759e-01],
        [ 2.3715e-01],
        [ 1.9429e-01],
        [ 4.3205e-01],
        [-7.5901e-01],
        [ 3.0543e-01],
        [ 5.7399e-01],
        [ 9.4501e-01],
        [ 7.4169e-01],
        [ 1.3863e+00],
        [-1.0016e+00],
        [-1.1097e+00],
        [ 1.8747e+00],
        [ 8.7505e-01],
        [-8.6521e-02],
        [ 1.1798e+00],
        [ 8.7663e-01],
        [ 7.5637e-01],
        [-2.7366e+00],
        [ 4.4466e-01],
        [ 6.1270e-01],
        [-1.3814e+00],
        [ 8.6757e-02],
        [ 5.3115e-01],
        [ 1.7756e+00],
        [ 5.4765e-02],
        [ 1.4058e-01],
        [-9.1508e-01],
        [ 1.1931e+00],
        [-7.8226e-01],
        [ 5.0210e-01],
        [-4.7745e-01],
        [-6.0741e-01],
        [-1

In [38]:
outputs5 = outputs3.reshape(256,-1)

In [43]:
outputs6 = torch.cat([outputs4, outputs5], dim=0)

In [45]:
outputs6.shape

torch.Size([512, 1])

In [47]:
targets = torch.randn(0,1, device=torch.device('cuda:0'))

In [48]:
targets

tensor([], device='cuda:0', size=(0, 1))

In [49]:
outputs7 = torch.cat([targets, outputs6], dim=0)

In [51]:
outputs7.shape

torch.Size([512, 1])

In [55]:
outputs8 = torch.randn(0,18, device=torch.device('cuda:0'))

In [56]:
outputs8

tensor([], device='cuda:0', size=(0, 18))

In [59]:
outputs9 = torch.randn(64,18, device=torch.device('cuda:0'))
outputs9.shape

torch.Size([64, 18])

In [61]:
outputs10 = torch.cat([outputs8, outputs9], dim=0)
outputs10.shape

torch.Size([64, 18])

In [62]:
outputs10 = torch.cat([outputs10, outputs9], dim=0)
outputs10.shape

torch.Size([128, 18])

In [64]:
outputs11 = torch.randn(0, device=torch.device('cuda:0'))
outputs11.shape

torch.Size([0])

In [65]:
outputs12 = torch.randn(64, device=torch.device('cuda:0'))
outputs12.shape

torch.Size([64])

In [66]:
outputs13 = torch.cat([outputs11, outputs12], dim=0)
outputs13.shape

NameError: name 'outputs11' is not defined